In [1]:
!pip install colormath 

  Created wheel for colormath: filename=colormath-3.0.0-py3-none-any.whl size=39392 sha256=05f948f199bbeffea4c0e7242bec353f617728e61201f6df20bdf2c852d5ca71
  Stored in directory: c:\users\ict01_03\appdata\local\pip\cache\wheels\ef\01\8a\75276fba001a7f0c94a243816973bc9f569475d8174f74377d
Successfully built colormath


In [83]:
estee_coolRGB = np.array([[227,184,151], [235,195,158], [205,151,117], [228,177,113], [221,164,110], [221,178,149], [193,152,109], [216,157,116], [207,162,145], [191,142,93]])
estee_warmRGB = np.array([[238,198,164], [242,200,173], [234,187,139], [222,172,114], [202,148,87], [208,159,98], [212,162,101], [211,153,88], [212,160,102]])

227

In [84]:
from colormath.color_objects import LabColor, sRGBColor 
from colormath.color_conversions import convert_color
import numpy as np

# RGB 컬러값을 LAB 컬러값으로 바꾸는 함수
def rgb2lab ( inputColor ) :

   num = 0
   RGB = [0, 0, 0]

   for value in inputColor :
       value = float(value) / 255

       if value > 0.04045 :
           value = ( ( value + 0.055 ) / 1.055 ) ** 2.4
       else :
           value = value / 12.92

       RGB[num] = value * 100
       num = num + 1

   XYZ = [0, 0, 0,]

   X = RGB [0] * 0.4124 + RGB [1] * 0.3576 + RGB [2] * 0.1805
   Y = RGB [0] * 0.2126 + RGB [1] * 0.7152 + RGB [2] * 0.0722
   Z = RGB [0] * 0.0193 + RGB [1] * 0.1192 + RGB [2] * 0.9505
   XYZ[ 0 ] = round( X, 4 )
   XYZ[ 1 ] = round( Y, 4 )
   XYZ[ 2 ] = round( Z, 4 )

   XYZ[ 0 ] = float( XYZ[ 0 ] ) / 95.047         # ref_X =  95.047   Observer= 2°, Illuminant= D65
   XYZ[ 1 ] = float( XYZ[ 1 ] ) / 100.0          # ref_Y = 100.000
   XYZ[ 2 ] = float( XYZ[ 2 ] ) / 108.883        # ref_Z = 108.883

   num = 0
   for value in XYZ :

       if value > 0.008856 :
           value = value ** ( 0.3333333333333333 )
       else :
           value = ( 7.787 * value ) + ( 16 / 116 )

       XYZ[num] = value
       num = num + 1

   Lab = [0, 0, 0]

   L = ( 116 * XYZ[ 1 ] ) - 16
   a = 500 * ( XYZ[ 0 ] - XYZ[ 1 ] )
   b = 200 * ( XYZ[ 1 ] - XYZ[ 2 ] )

   Lab [ 0 ] = round( L, 4 )
   Lab [ 1 ] = round( a, 4 )
   Lab [ 2 ] = round( b, 4 )

   return Lab

# RGB값이 담긴 넘파이 array를 통째로 LAB값으로 바꾸기
def npRGB2LAB(nparray):
    newarray = []
    for i in range(len(nparray)):
        newarray.append(rgb2lab((nparray[i,0], nparray[i,1], nparray[i,2])))
    print(np.around(newarray))

# RGB값이 담긴 리스트를 통째로 LAB값으로 바꾸기
def listRGB2LAB(RGBlist):
    newlist = []
    for i in range(len(RGBlist)):
        newlist.append(rgb2lab([RGBlist[i,0], RGBlist[i,1], RGBlist[i,2]]))
    return np.round(newlist,0)

In [88]:
estee_coolRGB = np.array([[227,184,151], [235,195,158], [205,151,117], [228,177,113], [221,164,110], [221,178,149], [193,152,109], [216,157,116], [207,162,145], [191,142,93]])
estee_warmRGB = np.array([[238,198,164], [242,200,173], [234,187,139], [222,172,114], [202,148,87], [208,159,98], [212,162,101], [211,153,88], [212,160,102]])

print(type(listRGB2LAB(estee_coolRGB)))
listRGB2LAB(estee_warmRGB)
# estee_coolRGB

<class 'numpy.ndarray'>


array([[83.,  9., 22.],
       [84., 11., 19.],
       [79., 11., 31.],
       [74., 11., 37.],
       [65., 14., 40.],
       [69., 11., 39.],
       [70., 11., 39.],
       [68., 15., 42.],
       [70., 12., 38.]])

In [105]:
npRGB2LAB(estee_coolRGB)

[[78. 11. 23.]
 [81.  9. 24.]
 [67. 16. 26.]
 [76. 11. 40.]
 [72. 15. 36.]
 [76. 12. 21.]
 [66. 10. 28.]
 [69. 17. 30.]
 [70. 14. 15.]
 [63. 13. 33.]]


In [36]:
estee_coolRGB = np.array([[227,184,151], [235,195,158], [205,151,117], [228,177,113], [221,164,110], [221,178,149], [193,152,109], [216,157,116], [207,162,145], [191,142,93]])
estee_warmRGB = np.array([[238,198,164], [242,200,173], [234,187,139], [222,172,114], [202,148,87], [208,159,98], [212,162,101], [211,153,88], [212,160,102]])

estee_cool =[]
for i in range(10):
    
    estee_cool.append(rgb2lab((estee_coolRGB[i,0], estee_coolRGB[i,1], estee_coolRGB[i,2])))


In [106]:
rgb = sRGBColor(222.5, 201.4, 188.9, is_upscaled=True)
lab = convert_color(rgb, LabColor, through_rgb_type=sRGBColor) 
print(lab)


LabColor (lab_l:82.5073 lab_a:5.3417 lab_b:8.9143)


In [ ]:
# 에스티로더 웜톤 쿨톤 색상 참조

# 10개
estee_coolRGB = [[227,184,151], [235,195,158], [205,151,117], [228,177,113], [221,164,110], [221,178,149], [193,152,109], [216,157,116], [207,162,145], [191,142,93]]

# 9개
estee_warmRGB = [[238,198,164], [242,200,173], [234,187,139], [222,172,114], [202,148,87], [208,159,98], [212,162,101], [211,153,88], [212,160,102]]


In [ ]:
# 기타 회사 파운데이션 RGB 컬러
더페이스샵 - 잉크래스팅 파운데이션 슬림핏 이엑스

쿨톤 : [236,207,191], [230,185,166], [220,165,143]
웜톤 : [228,193,165], [208,166,142]

에스쁘아 - 프로 테일러 파운데이션 비실크 SPF34 PA++
쿨톤 : C(P-핑크베이스) : [238,221,203], [246,220,203], [238,204,177], [235,189,156]
웜톤 : W(Y-옐로베이스): [251,232,202], [232,206,173], [233,207,174], [237,195,153]

* 구별 못 하겠는 거 : 허니[215,177,144], 딥[222,163,117]

에뛰드하우스 - 더블래스팅 파운데이션 NEW SPF42/PA++
쿨톤 : [253,223,198], [247,206,176], [243,200,168]
웜톤 : [254,218,176], [236,194,146], [236,181,125]